/**
 * Widget Data Contracts
 * 
 * TypeScript interfaces defining the data contract between the main app
 * and the widget extension. These types ensure type safety when querying
 * Tinybase store and passing props to widget components.
 * 
 * @module contracts/widget-props
 */

/**
 * View model for a single habit displayed in the widget.
 * Derived from joined query of habits, habitGroups, and checks tables.
 */
export interface HabitWidgetItem {
  /** Habit unique identifier (from habits table) */
  id: string;
  
  /** Habit display name */
  title: string;
  
  /** Hex color code for visual grouping indicator (e.g., "#FF5733") */
  color: string;
  
  /** Group identifier (null if ungrouped) */
  groupId?: string | null;

  /** Group name for display (null if ungrouped) */
  groupTitle?: string | null;
  
  /** Display order within widget (matches Today view order) */
  order: number;
}

/**
 * Complete state snapshot for widget rendering at a specific timestamp.
 * Generated by querying Tinybase store for current day's incomplete habits.
 */
export interface WidgetViewState {
  /** Ordered list of incomplete habits for today (limited to display capacity) */
  incompleteHabits: HabitWidgetItem[];
  
  /** Total count of incomplete habits (may exceed display capacity) */
  totalIncomplete: number;
  
  /** Whether all habits are completed for today */
  allComplete: boolean;
  
  /** Whether any habits exist (not deleted) */
  hasHabits: boolean;
  
  /** Timestamp when this state snapshot was created */
  generatedAt: Date;
}

/**
 * Widget size variant with corresponding display capacity.
 */
export type WidgetSize = 'small' | 'medium' | 'large';

/**
 * Maximum number of habits displayable per widget size.
 */
export const WIDGET_CAPACITY: Record<WidgetSize, number> = {
  small: 3,   // systemSmall: 2x2 grid
  medium: 6,  // systemMedium: 4x2 grid  
  large: 10,  // systemLarge: 4x4 grid
} as const;

/**
 * Props passed to the HabitWidget component by expo-widgets.
 * Extends WidgetBase from expo-widgets with widget-specific data.
 */
export interface HabitWidgetProps {
  /** Complete widget state snapshot */
  viewState: WidgetViewState;
  
  /** Number of habits to display (capped at widget capacity) */
  displayCount: number;
}

/**
 * Deep link URL actions for widget interactions.
 * Note: Habit completion happens in widget background (direct write to shared store).
 */
export const WidgetDeepLinks = {
  /** Open app to Today view: beebloom://today */
  openToday: () => 'beebloom://today',
} as const;

/**
 * Widget configuration matching app.json expo-widgets plugin settings.
 */
export const WidgetConfig = {
  /** Widget identifier (must match app.json widgets[].name) */
  name: 'HabitWidget',
  
  /** User-facing widget name in widget gallery */
  displayName: 'BeeBloom Habits',
  
  /** Widget description in widget gallery */
  description: 'Complete your daily habits',
  
  /** Supported widget sizes */
  supportedFamilies: ['systemSmall', 'systemMedium', 'systemLarge'] as const,
  
  /** App Group identifier for shared storage */
  groupIdentifier: 'group.com.ilyakukarkinorg.beebloom',
  
  /** Widget extension bundle identifier */
  bundleIdentifier: 'com.ilyakukarkinorg.beebloom.widgets',
} as const;

/**
 * Timeline refresh configuration.
 */
export const TimelineConfig = {
  /** Refresh interval in milliseconds (15 minutes) */
  refreshInterval: 15 * 60 * 1000,
  
  /** Number of timeline entries to generate */
  entryCount: 5,
  
  /** Maximum retry attempts for failed updates */
  maxRetries: 3,
  
  /** Retry delay in milliseconds */
  retryDelay: 5000,
} as const;
